### ISSUE TITLE
'copy' action for rules disregards pre/post parameter for the destination device group

### ISSUE THREAD

**Issue by nikmat1** [swaschkut/pan-os-php#15]
Hi Sven,

When I run a command along these lines:

`pan-os-php in=api://<panorama_10.2> type=rule location=<source_device_group> ruletype=security 'actions=copy:<destination device group>,pre' 'filter=<my filter>'`

All rules from `<source_device_group>/POST` (as per the filter) end up in the **POST** section of the destination group despite the **PRE** argument specified in the copy action.

Interestingly enough, as the tool executes it gives the correct output for each rule as follows:

`- object '<rule name>'  passing through Action='copy' Args: location=<destination device group>, preORpost=pre, `

(despite that, the rule gets placed into the **POST** section as it was in the source device group)

Can you investigate this one, please?

**Comment by swaschkut** [comment]
Hi,

thanks for finding this bug, which is "ONLY" available in API mode.

I just right now pushed a new develop Docker container version,
where I like to ask, if you can validate this new version and if this bug is also fixed for you.

I tested this against Panorama 11.1.x and 11.2.x

docker pull swaschkut/pan-os-php:develop
docker run --name panosphp --rm -v ${PWD}:/share -it swaschkut/pan-os-php:develop


the develop docker container is still on pan-os-php version 2.1.24


you can validate the behaviour if you add "debugapi" as an argument to your command:

`pan-os-php in=api://<panorama_10.2> type=rule location=<source_device_group> ruletype=security 'actions=copy:<destination device group>,pre' 'filter=<my filter>' debugapi`

**Comment by nikmat1** [comment]
I wish Palo TAC was that quick with their responses :)

I will test it later and let you know the outcome. THANK YOU!

**Comment by swaschkut** [comment]
bugfix published with #16
